export default {
  total: 4,
  items: [
    {
      userId: 1,
      tenantId: null,
      deptId: 103,
      userName: 'admin',
      nickName: 'LinaBell',
      userType: null,
      email: 'crazyLionLi@163.com',
      phonenumber: '15888888888',
      sex: null,
      avatar: null,
      status: '0',
      loginIp: null,
      loginDate: null,
      remark: null,
      createTime: '2023-11-25 13:06:29',
      deptName: '研发部门',
      roles: null,
      roleIds: null,
      postIds: null,
      roleId: null,
    },
    {
      userId: 3,
      tenantId: null,
      deptId: 108,
      userName: 'test',
      nickName: '工作流测试 密码666666',
      userType: null,
      email: '',
      phonenumber: '',
      sex: null,
      avatar: null,
      status: '0',
      loginIp: null,
      loginDate: null,
      remark: null,
      createTime: '2024-05-02 14:12:18',
      deptName: '市场部门',
      roles: null,
      roleIds: null,
      postIds: null,
      roleId: null,
    },
    {
      userId: 4,
      tenantId: null,
      deptId: 102,
      userName: 'test1',
      nickName: '仅本人 密码666666',
      userType: null,
      email: '',
      phonenumber: '',
      sex: null,
      avatar: null,
      status: '0',
      loginIp: null,
      loginDate: null,
      remark: null,
      createTime: '2024-05-02 14:12:18',
      deptName: '长沙分公司',
      roles: null,
      roleIds: null,
      postIds: null,
      roleId: null,
    },
    {
      userId: 666,
      tenantId: null,
      deptId: 100,
      userName: 'dapdap',
      nickName: '玲娜贝儿',
      userType: null,
      email: '12345@1253.com',
      phonenumber: '18888888888',
      sex: null,
      avatar: null,
      status: '0',
      loginIp: null,
      loginDate: null,
      remark: null,
      createTime: '2024-06-01 09:17:36',
      deptName: 'XXX科技',
      roles: null,
      roleIds: null,
      postIds: null,
      roleId: null,
    },
  ],
  code: 200,
  msg: '查询成功',
};
