export default {
  total: 2,
  items: [
    {
      userId: 2,
      tenantId: null,
      deptId: 105,
      userName: 'lionli',
      nickName: '疯狂的贝er',
      userType: null,
      email: 'crazyLionLi@qq.com',
      phonenumber: '15666666666',
      sex: null,
      avatar: null,
      status: '0',
      loginIp: null,
      loginDate: null,
      remark: null,
      createTime: '2023-11-25 13:06:29',
      deptName: '测试部门',
      roles: null,
      roleIds: null,
      postIds: null,
      roleId: null,
    },
    {
      userId: '1843733766566641666',
      tenantId: null,
      deptId: 103,
      userName: '1123333',
      nickName: '11',
      userType: null,
      email: '',
      phonenumber: '',
      sex: null,
      avatar: null,
      status: '0',
      loginIp: null,
      loginDate: null,
      remark: null,
      createTime: '2024-10-09 03:22:40',
      deptName: '研发部门',
      roles: null,
      roleIds: null,
      postIds: null,
      roleId: null,
    },
  ],
  code: 200,
  msg: '查询成功',
};
