export const roleMenuTreeselectData = {
  code: 200,
  msg: '操作成功',
  data: {
    checkedKeys: [
      113, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011,
      1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023,
      1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035,
      1036, 1037, 1038, 1039, 1046, 1047, 1048, 1055, 1056, 1058, 1057, 1059,
      1060, 1061, 1062, 1063, 1064, 1065, 1040, 1041, 1042, 1043, 1044, 1045,
      1050,
    ],
    menus: [
      {
        id: 1,
        parentId: 0,
        label: 'menu.system.root',
        weight: 1,
        children: [
          {
            id: 100,
            parentId: 1,
            label: 'menu.system.user',
            weight: 1,
            children: [
              {
                id: 1001,
                parentId: 100,
                label: '用户查询',
                weight: 1,
              },
              {
                id: 1002,
                parentId: 100,
                label: '用户新增',
                weight: 2,
              },
              {
                id: 1003,
                parentId: 100,
                label: '用户修改',
                weight: 3,
              },
              {
                id: 1004,
                parentId: 100,
                label: '用户删除',
                weight: 4,
              },
              {
                id: 1005,
                parentId: 100,
                label: '用户导出',
                weight: 5,
              },
              {
                id: 1006,
                parentId: 100,
                label: '用户导入',
                weight: 6,
              },
              {
                id: 1007,
                parentId: 100,
                label: '重置密码',
                weight: 7,
              },
            ],
          },
          {
            id: 101,
            parentId: 1,
            label: 'menu.system.role',
            weight: 2,
            children: [
              {
                id: 1008,
                parentId: 101,
                label: '角色查询',
                weight: 1,
              },
              {
                id: 1009,
                parentId: 101,
                label: '角色新增',
                weight: 2,
              },
              {
                id: 1010,
                parentId: 101,
                label: '角色修改',
                weight: 3,
              },
              {
                id: 1011,
                parentId: 101,
                label: '角色删除',
                weight: 4,
              },
              {
                id: 1012,
                parentId: 101,
                label: '角色导出',
                weight: 5,
              },
            ],
          },
          {
            id: 102,
            parentId: 1,
            label: 'menu.system.menu',
            weight: 3,
            children: [
              {
                id: 1013,
                parentId: 102,
                label: '菜单查询',
                weight: 1,
              },
              {
                id: 1014,
                parentId: 102,
                label: '菜单新增',
                weight: 2,
              },
              {
                id: 1015,
                parentId: 102,
                label: '菜单修改',
                weight: 3,
              },
              {
                id: 1016,
                parentId: 102,
                label: '菜单删除',
                weight: 4,
              },
            ],
          },
          {
            id: 103,
            parentId: 1,
            label: 'menu.system.dept',
            weight: 4,
            children: [
              {
                id: 1017,
                parentId: 103,
                label: '部门查询',
                weight: 1,
              },
              {
                id: 1018,
                parentId: 103,
                label: '部门新增',
                weight: 2,
              },
              {
                id: 1019,
                parentId: 103,
                label: '部门修改',
                weight: 3,
              },
              {
                id: 1020,
                parentId: 103,
                label: '部门删除',
                weight: 4,
              },
            ],
          },
          {
            id: 104,
            parentId: 1,
            label: 'menu.system.post',
            weight: 5,
            children: [
              {
                id: 1021,
                parentId: 104,
                label: '岗位查询',
                weight: 1,
              },
              {
                id: 1022,
                parentId: 104,
                label: '岗位新增',
                weight: 2,
              },
              {
                id: 1023,
                parentId: 104,
                label: '岗位修改',
                weight: 3,
              },
              {
                id: 1024,
                parentId: 104,
                label: '岗位删除',
                weight: 4,
              },
              {
                id: 1025,
                parentId: 104,
                label: '岗位导出',
                weight: 5,
              },
            ],
          },
          {
            id: 105,
            parentId: 1,
            label: 'menu.system.dict',
            weight: 6,
            children: [
              {
                id: 1026,
                parentId: 105,
                label: '字典查询',
                weight: 1,
              },
              {
                id: 1027,
                parentId: 105,
                label: '字典新增',
                weight: 2,
              },
              {
                id: 1028,
                parentId: 105,
                label: '字典修改',
                weight: 3,
              },
              {
                id: 1029,
                parentId: 105,
                label: '字典删除',
                weight: 4,
              },
              {
                id: 1030,
                parentId: 105,
                label: '字典导出',
                weight: 5,
              },
            ],
          },
          {
            id: 106,
            parentId: 1,
            label: 'menu.system.config',
            weight: 7,
            children: [
              {
                id: 1031,
                parentId: 106,
                label: '参数查询',
                weight: 1,
              },
              {
                id: 1032,
                parentId: 106,
                label: '参数新增',
                weight: 2,
              },
              {
                id: 1033,
                parentId: 106,
                label: '参数修改',
                weight: 3,
              },
              {
                id: 1034,
                parentId: 106,
                label: '参数删除',
                weight: 4,
              },
              {
                id: 1035,
                parentId: 106,
                label: '参数导出',
                weight: 5,
              },
            ],
          },
          {
            id: 107,
            parentId: 1,
            label: 'menu.system.notice',
            weight: 8,
            children: [
              {
                id: 1036,
                parentId: 107,
                label: '公告查询',
                weight: 1,
              },
              {
                id: 1037,
                parentId: 107,
                label: '公告新增',
                weight: 2,
              },
              {
                id: 1038,
                parentId: 107,
                label: '公告修改',
                weight: 3,
              },
              {
                id: 1039,
                parentId: 107,
                label: '公告删除',
                weight: 4,
              },
            ],
          },
          {
            id: 108,
            parentId: 1,
            label: 'menu.system.log.root',
            weight: 9,
            children: [
              {
                id: 500,
                parentId: 108,
                label: 'menu.system.log.operation',
                weight: 1,
                children: [
                  {
                    id: 1040,
                    parentId: 500,
                    label: '操作查询',
                    weight: 1,
                  },
                  {
                    id: 1041,
                    parentId: 500,
                    label: '操作删除',
                    weight: 2,
                  },
                  {
                    id: 1042,
                    parentId: 500,
                    label: '日志导出',
                    weight: 4,
                  },
                ],
              },
              {
                id: 501,
                parentId: 108,
                label: 'menu.system.log.login',
                weight: 2,
                children: [
                  {
                    id: 1043,
                    parentId: 501,
                    label: '登录查询',
                    weight: 1,
                  },
                  {
                    id: 1044,
                    parentId: 501,
                    label: '登录删除',
                    weight: 2,
                  },
                  {
                    id: 1045,
                    parentId: 501,
                    label: '日志导出',
                    weight: 3,
                  },
                  {
                    id: 1050,
                    parentId: 501,
                    label: '账户解锁',
                    weight: 4,
                  },
                ],
              },
            ],
          },
          {
            id: 118,
            parentId: 1,
            label: 'menu.system.oss',
            weight: 10,
            children: [
              {
                id: 1600,
                parentId: 118,
                label: '文件查询',
                weight: 1,
              },
              {
                id: 1601,
                parentId: 118,
                label: '文件上传',
                weight: 2,
              },
              {
                id: 1602,
                parentId: 118,
                label: '文件下载',
                weight: 3,
              },
              {
                id: 1603,
                parentId: 118,
                label: '文件删除',
                weight: 4,
              },
              {
                id: 1620,
                parentId: 118,
                label: '配置列表',
                weight: 5,
              },
              {
                id: 1621,
                parentId: 118,
                label: '配置添加',
                weight: 6,
              },
              {
                id: 1622,
                parentId: 118,
                label: '配置编辑',
                weight: 6,
              },
              {
                id: 1623,
                parentId: 118,
                label: '配置删除',
                weight: 6,
              },
            ],
          },
          {
            id: 123,
            parentId: 1,
            label: 'menu.system.client',
            weight: 11,
            children: [
              {
                id: 1061,
                parentId: 123,
                label: '客户端管理查询',
                weight: 1,
              },
              {
                id: 1062,
                parentId: 123,
                label: '客户端管理新增',
                weight: 2,
              },
              {
                id: 1063,
                parentId: 123,
                label: '客户端管理修改',
                weight: 3,
              },
              {
                id: 1064,
                parentId: 123,
                label: '客户端管理删除',
                weight: 4,
              },
              {
                id: 1065,
                parentId: 123,
                label: '客户端管理导出',
                weight: 5,
              },
            ],
          },
        ],
      },
      {
        id: 6,
        parentId: 0,
        label: 'menu.tenant.root',
        weight: 2,
        children: [
          {
            id: 121,
            parentId: 6,
            label: 'menu.tenant.root',
            weight: 1,
            children: [
              {
                id: 1606,
                parentId: 121,
                label: '租户查询',
                weight: 1,
              },
              {
                id: 1607,
                parentId: 121,
                label: '租户新增',
                weight: 2,
              },
              {
                id: 1608,
                parentId: 121,
                label: '租户修改',
                weight: 3,
              },
              {
                id: 1609,
                parentId: 121,
                label: '租户删除',
                weight: 4,
              },
              {
                id: 1610,
                parentId: 121,
                label: '租户导出',
                weight: 5,
              },
            ],
          },
          {
            id: 122,
            parentId: 6,
            label: 'menu.tenant.package',
            weight: 2,
            children: [
              {
                id: 1611,
                parentId: 122,
                label: '租户套餐查询',
                weight: 1,
              },
              {
                id: 1612,
                parentId: 122,
                label: '租户套餐新增',
                weight: 2,
              },
              {
                id: 1613,
                parentId: 122,
                label: '租户套餐修改',
                weight: 3,
              },
              {
                id: 1614,
                parentId: 122,
                label: '租户套餐删除',
                weight: 4,
              },
              {
                id: 1615,
                parentId: 122,
                label: '租户套餐导出',
                weight: 5,
              },
            ],
          },
        ],
      },
      {
        id: 2,
        parentId: 0,
        label: 'menu.monitor.root',
        weight: 3,
        children: [
          {
            id: 109,
            parentId: 2,
            label: 'menu.monitor.online',
            weight: 1,
            children: [
              {
                id: 1046,
                parentId: 109,
                label: '在线查询',
                weight: 1,
              },
              {
                id: 1047,
                parentId: 109,
                label: '批量强退',
                weight: 2,
              },
              {
                id: 1048,
                parentId: 109,
                label: '单条强退',
                weight: 3,
              },
            ],
          },
          {
            id: 113,
            parentId: 2,
            label: 'menu.monitor.cache',
            weight: 5,
          },
          {
            id: 117,
            parentId: 2,
            label: 'menu.monitor.admin',
            weight: 5,
          },
          {
            id: 120,
            parentId: 2,
            label: 'menu.monitor.job',
            weight: 5,
          },
        ],
      },
      {
        id: 3,
        parentId: 0,
        label: 'menu.tool.root',
        weight: 4,
        children: [
          {
            id: 115,
            parentId: 3,
            label: 'menu.tool.gen',
            weight: 2,
            children: [
              {
                id: 1055,
                parentId: 115,
                label: '生成查询',
                weight: 1,
              },
              {
                id: 1056,
                parentId: 115,
                label: '生成修改',
                weight: 2,
              },
              {
                id: 1058,
                parentId: 115,
                label: '导入代码',
                weight: 2,
              },
              {
                id: 1057,
                parentId: 115,
                label: '生成删除',
                weight: 3,
              },
              {
                id: 1059,
                parentId: 115,
                label: '预览代码',
                weight: 4,
              },
              {
                id: 1060,
                parentId: 115,
                label: '生成代码',
                weight: 5,
              },
            ],
          },
        ],
      },
      {
        id: '1794635477926084610',
        parentId: 0,
        label: '流程发起',
        weight: 5,
        children: [
          {
            id: '1794636509859086338',
            parentId: '1794635477926084610',
            label: '采购流程(子表单)',
            weight: 2,
          },
          {
            id: 11_638,
            parentId: '1794635477926084610',
            label: '请假申请',
            weight: 5,
            children: [
              {
                id: 11_639,
                parentId: 11_638,
                label: '请假申请查询',
                weight: 1,
              },
              {
                id: 11_640,
                parentId: 11_638,
                label: '请假申请新增',
                weight: 2,
              },
              {
                id: 11_641,
                parentId: 11_638,
                label: '请假申请修改',
                weight: 3,
              },
              {
                id: 11_642,
                parentId: 11_638,
                label: '请假申请删除',
                weight: 4,
              },
              {
                id: 11_643,
                parentId: 11_638,
                label: '请假申请导出',
                weight: 5,
              },
            ],
          },
        ],
      },
      {
        id: 11_616,
        parentId: 0,
        label: 'menu.workflow.root',
        weight: 6,
        children: [
          {
            id: 11_622,
            parentId: 11_616,
            label: 'menu.workflow.category',
            weight: 1,
            children: [
              {
                id: 11_623,
                parentId: 11_622,
                label: '流程分类查询',
                weight: 1,
              },
              {
                id: 11_624,
                parentId: 11_622,
                label: '流程分类新增',
                weight: 2,
              },
              {
                id: 11_625,
                parentId: 11_622,
                label: '流程分类修改',
                weight: 3,
              },
              {
                id: 11_626,
                parentId: 11_622,
                label: '流程分类删除',
                weight: 4,
              },
              {
                id: 11_627,
                parentId: 11_622,
                label: '流程分类导出',
                weight: 5,
              },
            ],
          },
          {
            id: 11_617,
            parentId: 11_616,
            label: 'menu.workflow.model',
            weight: 2,
          },
          {
            id: 11_620,
            parentId: 11_616,
            label: 'menu.workflow.define',
            weight: 3,
          },
          {
            id: 11_630,
            parentId: 11_616,
            label: 'menu.workflow.monitor.root',
            weight: 4,
            children: [
              {
                id: 11_621,
                parentId: 11_630,
                label: 'menu.workflow.monitor.instance',
                weight: 1,
              },
              {
                id: 11_631,
                parentId: 11_630,
                label: 'menu.workflow.monitor.todo',
                weight: 2,
              },
            ],
          },
          {
            id: 11_628,
            parentId: 11_616,
            label: 'menu.workflow.form',
            weight: 5,
            children: [
              {
                id: 11_644,
                parentId: 11_628,
                label: '表单管理查询',
                weight: 1,
              },
              {
                id: 11_645,
                parentId: 11_628,
                label: '表单管理新增',
                weight: 2,
              },
              {
                id: 11_646,
                parentId: 11_628,
                label: '表单管理修改',
                weight: 3,
              },
              {
                id: 11_647,
                parentId: 11_628,
                label: '表单管理删除',
                weight: 4,
              },
              {
                id: 11_648,
                parentId: 11_628,
                label: '表单管理导出',
                weight: 5,
              },
            ],
          },
        ],
      },
      {
        id: 11_618,
        parentId: 0,
        label: 'menu.task.root',
        weight: 7,
        children: [
          {
            id: 11_629,
            parentId: 11_618,
            label: 'menu.task.apply',
            weight: 1,
          },
          {
            id: 11_619,
            parentId: 11_618,
            label: 'menu.task.todo',
            weight: 2,
          },
          {
            id: 11_632,
            parentId: 11_618,
            label: 'menu.task.done',
            weight: 3,
          },
          {
            id: 11_633,
            parentId: 11_618,
            label: 'menu.task.cc',
            weight: 4,
          },
        ],
      },
      {
        id: '1752717490914430978',
        parentId: 0,
        label: '非官方功能',
        weight: 8,
        children: [
          {
            id: '1752717707583787010',
            parentId: '1752717490914430978',
            label: '访问统计',
            weight: 1,
          },
          {
            id: '1728330982004617217',
            parentId: '1752717490914430978',
            label: '发送消息测试',
            weight: 8,
          },
          {
            id: '1801920385979580417',
            parentId: '1752717490914430978',
            label: '文件上传demo',
            weight: 9,
          },
          {
            id: '1808401715449401345',
            parentId: '1752717490914430978',
            label: '富文本编辑器',
            weight: 10,
          },
          {
            id: '1804484510018502658',
            parentId: '1752717490914430978',
            label: '更新日志',
            weight: 22,
          },
          {
            id: '1844262955958992898',
            parentId: '1752717490914430978',
            label: '路由参数示例',
            weight: 23,
          },
        ],
      },
      {
        id: '1754765339911098369',
        parentId: 0,
        label: '微信群',
        weight: 9,
      },
      {
        id: '1746459036148088834',
        parentId: 0,
        label: '外链测试',
        weight: 11,
        children: [
          {
            id: '1746460396327321602',
            parentId: '1746459036148088834',
            label: '项目地址(外链)',
            weight: 1,
          },
          {
            id: '1746459334774145025',
            parentId: '1746459036148088834',
            label: '官方文档(内嵌)',
            weight: 2,
          },
          {
            id: '1760597980791017474',
            parentId: '1746459036148088834',
            label: 'PULS官网',
            weight: 10,
          },
        ],
      },
    ],
  },
};

export const treeSelectData = {
  code: 200,
  msg: '操作成功',
  data: [
    {
      id: 1,
      parentId: 0,
      label: 'menu.system.root',
      weight: 1,
      children: [
        {
          id: 100,
          parentId: 1,
          label: 'menu.system.user',
          weight: 1,
          children: [
            {
              id: 1001,
              parentId: 100,
              label: '用户查询',
              weight: 1,
            },
            {
              id: 1002,
              parentId: 100,
              label: '用户新增',
              weight: 2,
            },
            {
              id: 1003,
              parentId: 100,
              label: '用户修改',
              weight: 3,
            },
            {
              id: 1004,
              parentId: 100,
              label: '用户删除',
              weight: 4,
            },
            {
              id: 1005,
              parentId: 100,
              label: '用户导出',
              weight: 5,
            },
            {
              id: 1006,
              parentId: 100,
              label: '用户导入',
              weight: 6,
            },
            {
              id: 1007,
              parentId: 100,
              label: '重置密码',
              weight: 7,
            },
          ],
        },
        {
          id: 101,
          parentId: 1,
          label: 'menu.system.role',
          weight: 2,
          children: [
            {
              id: 1008,
              parentId: 101,
              label: '角色查询',
              weight: 1,
            },
            {
              id: 1009,
              parentId: 101,
              label: '角色新增',
              weight: 2,
            },
            {
              id: 1010,
              parentId: 101,
              label: '角色修改',
              weight: 3,
            },
            {
              id: 1011,
              parentId: 101,
              label: '角色删除',
              weight: 4,
            },
            {
              id: 1012,
              parentId: 101,
              label: '角色导出',
              weight: 5,
            },
          ],
        },
        {
          id: 102,
          parentId: 1,
          label: 'menu.system.menu',
          weight: 3,
          children: [
            {
              id: 1013,
              parentId: 102,
              label: '菜单查询',
              weight: 1,
            },
            {
              id: 1014,
              parentId: 102,
              label: '菜单新增',
              weight: 2,
            },
            {
              id: 1015,
              parentId: 102,
              label: '菜单修改',
              weight: 3,
            },
            {
              id: 1016,
              parentId: 102,
              label: '菜单删除',
              weight: 4,
            },
          ],
        },
        {
          id: 103,
          parentId: 1,
          label: 'menu.system.dept',
          weight: 4,
          children: [
            {
              id: 1017,
              parentId: 103,
              label: '部门查询',
              weight: 1,
            },
            {
              id: 1018,
              parentId: 103,
              label: '部门新增',
              weight: 2,
            },
            {
              id: 1019,
              parentId: 103,
              label: '部门修改',
              weight: 3,
            },
            {
              id: 1020,
              parentId: 103,
              label: '部门删除',
              weight: 4,
            },
          ],
        },
        {
          id: 104,
          parentId: 1,
          label: 'menu.system.post',
          weight: 5,
          children: [
            {
              id: 1021,
              parentId: 104,
              label: '岗位查询',
              weight: 1,
            },
            {
              id: 1022,
              parentId: 104,
              label: '岗位新增',
              weight: 2,
            },
            {
              id: 1023,
              parentId: 104,
              label: '岗位修改',
              weight: 3,
            },
            {
              id: 1024,
              parentId: 104,
              label: '岗位删除',
              weight: 4,
            },
            {
              id: 1025,
              parentId: 104,
              label: '岗位导出',
              weight: 5,
            },
          ],
        },
        {
          id: 105,
          parentId: 1,
          label: 'menu.system.dict',
          weight: 6,
          children: [
            {
              id: 1026,
              parentId: 105,
              label: '字典查询',
              weight: 1,
            },
            {
              id: 1027,
              parentId: 105,
              label: '字典新增',
              weight: 2,
            },
            {
              id: 1028,
              parentId: 105,
              label: '字典修改',
              weight: 3,
            },
            {
              id: 1029,
              parentId: 105,
              label: '字典删除',
              weight: 4,
            },
            {
              id: 1030,
              parentId: 105,
              label: '字典导出',
              weight: 5,
            },
          ],
        },
        {
          id: 106,
          parentId: 1,
          label: 'menu.system.config',
          weight: 7,
          children: [
            {
              id: 1031,
              parentId: 106,
              label: '参数查询',
              weight: 1,
            },
            {
              id: 1032,
              parentId: 106,
              label: '参数新增',
              weight: 2,
            },
            {
              id: 1033,
              parentId: 106,
              label: '参数修改',
              weight: 3,
            },
            {
              id: 1034,
              parentId: 106,
              label: '参数删除',
              weight: 4,
            },
            {
              id: 1035,
              parentId: 106,
              label: '参数导出',
              weight: 5,
            },
          ],
        },
        {
          id: 107,
          parentId: 1,
          label: 'menu.system.notice',
          weight: 8,
          children: [
            {
              id: 1036,
              parentId: 107,
              label: '公告查询',
              weight: 1,
            },
            {
              id: 1037,
              parentId: 107,
              label: '公告新增',
              weight: 2,
            },
            {
              id: 1038,
              parentId: 107,
              label: '公告修改',
              weight: 3,
            },
            {
              id: 1039,
              parentId: 107,
              label: '公告删除',
              weight: 4,
            },
          ],
        },
        {
          id: 108,
          parentId: 1,
          label: 'menu.system.log.root',
          weight: 9,
          children: [
            {
              id: 500,
              parentId: 108,
              label: 'menu.system.log.operation',
              weight: 1,
              children: [
                {
                  id: 1040,
                  parentId: 500,
                  label: '操作查询',
                  weight: 1,
                },
                {
                  id: 1041,
                  parentId: 500,
                  label: '操作删除',
                  weight: 2,
                },
                {
                  id: 1042,
                  parentId: 500,
                  label: '日志导出',
                  weight: 4,
                },
              ],
            },
            {
              id: 501,
              parentId: 108,
              label: 'menu.system.log.login',
              weight: 2,
              children: [
                {
                  id: 1043,
                  parentId: 501,
                  label: '登录查询',
                  weight: 1,
                },
                {
                  id: 1044,
                  parentId: 501,
                  label: '登录删除',
                  weight: 2,
                },
                {
                  id: 1045,
                  parentId: 501,
                  label: '日志导出',
                  weight: 3,
                },
                {
                  id: 1050,
                  parentId: 501,
                  label: '账户解锁',
                  weight: 4,
                },
              ],
            },
          ],
        },
        {
          id: 118,
          parentId: 1,
          label: 'menu.system.oss',
          weight: 10,
          children: [
            {
              id: 1600,
              parentId: 118,
              label: '文件查询',
              weight: 1,
            },
            {
              id: 1601,
              parentId: 118,
              label: '文件上传',
              weight: 2,
            },
            {
              id: 1602,
              parentId: 118,
              label: '文件下载',
              weight: 3,
            },
            {
              id: 1603,
              parentId: 118,
              label: '文件删除',
              weight: 4,
            },
            {
              id: 1620,
              parentId: 118,
              label: '配置列表',
              weight: 5,
            },
            {
              id: 1621,
              parentId: 118,
              label: '配置添加',
              weight: 6,
            },
            {
              id: 1622,
              parentId: 118,
              label: '配置编辑',
              weight: 6,
            },
            {
              id: 1623,
              parentId: 118,
              label: '配置删除',
              weight: 6,
            },
          ],
        },
        {
          id: 123,
          parentId: 1,
          label: 'menu.system.client',
          weight: 11,
          children: [
            {
              id: 1061,
              parentId: 123,
              label: '客户端管理查询',
              weight: 1,
            },
            {
              id: 1062,
              parentId: 123,
              label: '客户端管理新增',
              weight: 2,
            },
            {
              id: 1063,
              parentId: 123,
              label: '客户端管理修改',
              weight: 3,
            },
            {
              id: 1064,
              parentId: 123,
              label: '客户端管理删除',
              weight: 4,
            },
            {
              id: 1065,
              parentId: 123,
              label: '客户端管理导出',
              weight: 5,
            },
          ],
        },
      ],
    },
    {
      id: 6,
      parentId: 0,
      label: 'menu.tenant.root',
      weight: 2,
      children: [
        {
          id: 121,
          parentId: 6,
          label: 'menu.tenant.root',
          weight: 1,
          children: [
            {
              id: 1606,
              parentId: 121,
              label: '租户查询',
              weight: 1,
            },
            {
              id: 1607,
              parentId: 121,
              label: '租户新增',
              weight: 2,
            },
            {
              id: 1608,
              parentId: 121,
              label: '租户修改',
              weight: 3,
            },
            {
              id: 1609,
              parentId: 121,
              label: '租户删除',
              weight: 4,
            },
            {
              id: 1610,
              parentId: 121,
              label: '租户导出',
              weight: 5,
            },
          ],
        },
        {
          id: 122,
          parentId: 6,
          label: 'menu.tenant.package',
          weight: 2,
          children: [
            {
              id: 1611,
              parentId: 122,
              label: '租户套餐查询',
              weight: 1,
            },
            {
              id: 1612,
              parentId: 122,
              label: '租户套餐新增',
              weight: 2,
            },
            {
              id: 1613,
              parentId: 122,
              label: '租户套餐修改',
              weight: 3,
            },
            {
              id: 1614,
              parentId: 122,
              label: '租户套餐删除',
              weight: 4,
            },
            {
              id: 1615,
              parentId: 122,
              label: '租户套餐导出',
              weight: 5,
            },
          ],
        },
      ],
    },
    {
      id: 2,
      parentId: 0,
      label: 'menu.monitor.root',
      weight: 3,
      children: [
        {
          id: 109,
          parentId: 2,
          label: 'menu.monitor.online',
          weight: 1,
          children: [
            {
              id: 1046,
              parentId: 109,
              label: '在线查询',
              weight: 1,
            },
            {
              id: 1047,
              parentId: 109,
              label: '批量强退',
              weight: 2,
            },
            {
              id: 1048,
              parentId: 109,
              label: '单条强退',
              weight: 3,
            },
          ],
        },
        {
          id: 113,
          parentId: 2,
          label: 'menu.monitor.cache',
          weight: 5,
        },
        {
          id: 117,
          parentId: 2,
          label: 'menu.monitor.admin',
          weight: 5,
        },
        {
          id: 120,
          parentId: 2,
          label: 'menu.monitor.job',
          weight: 5,
        },
      ],
    },
    {
      id: 3,
      parentId: 0,
      label: 'menu.tool.root',
      weight: 4,
      children: [
        {
          id: 115,
          parentId: 3,
          label: 'menu.tool.gen',
          weight: 2,
          children: [
            {
              id: 1055,
              parentId: 115,
              label: '生成查询',
              weight: 1,
            },
            {
              id: 1056,
              parentId: 115,
              label: '生成修改',
              weight: 2,
            },
            {
              id: 1058,
              parentId: 115,
              label: '导入代码',
              weight: 2,
            },
            {
              id: 1057,
              parentId: 115,
              label: '生成删除',
              weight: 3,
            },
            {
              id: 1059,
              parentId: 115,
              label: '预览代码',
              weight: 4,
            },
            {
              id: 1060,
              parentId: 115,
              label: '生成代码',
              weight: 5,
            },
          ],
        },
      ],
    },
    {
      id: '1794635477926084610',
      parentId: 0,
      label: '流程发起',
      weight: 5,
      children: [
        {
          id: '1794636509859086338',
          parentId: '1794635477926084610',
          label: '采购流程(子表单)',
          weight: 2,
        },
        {
          id: 11_638,
          parentId: '1794635477926084610',
          label: '请假申请',
          weight: 5,
          children: [
            {
              id: 11_639,
              parentId: 11_638,
              label: '请假申请查询',
              weight: 1,
            },
            {
              id: 11_640,
              parentId: 11_638,
              label: '请假申请新增',
              weight: 2,
            },
            {
              id: 11_641,
              parentId: 11_638,
              label: '请假申请修改',
              weight: 3,
            },
            {
              id: 11_642,
              parentId: 11_638,
              label: '请假申请删除',
              weight: 4,
            },
            {
              id: 11_643,
              parentId: 11_638,
              label: '请假申请导出',
              weight: 5,
            },
          ],
        },
      ],
    },
    {
      id: 11_616,
      parentId: 0,
      label: 'menu.workflow.root',
      weight: 6,
      children: [
        {
          id: 11_622,
          parentId: 11_616,
          label: 'menu.workflow.category',
          weight: 1,
          children: [
            {
              id: 11_623,
              parentId: 11_622,
              label: '流程分类查询',
              weight: 1,
            },
            {
              id: 11_624,
              parentId: 11_622,
              label: '流程分类新增',
              weight: 2,
            },
            {
              id: 11_625,
              parentId: 11_622,
              label: '流程分类修改',
              weight: 3,
            },
            {
              id: 11_626,
              parentId: 11_622,
              label: '流程分类删除',
              weight: 4,
            },
            {
              id: 11_627,
              parentId: 11_622,
              label: '流程分类导出',
              weight: 5,
            },
          ],
        },
        {
          id: 11_617,
          parentId: 11_616,
          label: 'menu.workflow.model',
          weight: 2,
        },
        {
          id: 11_620,
          parentId: 11_616,
          label: 'menu.workflow.define',
          weight: 3,
        },
        {
          id: 11_630,
          parentId: 11_616,
          label: 'menu.workflow.monitor.root',
          weight: 4,
          children: [
            {
              id: 11_621,
              parentId: 11_630,
              label: 'menu.workflow.monitor.instance',
              weight: 1,
            },
            {
              id: 11_631,
              parentId: 11_630,
              label: 'menu.workflow.monitor.todo',
              weight: 2,
            },
          ],
        },
        {
          id: 11_628,
          parentId: 11_616,
          label: 'menu.workflow.form',
          weight: 5,
          children: [
            {
              id: 11_644,
              parentId: 11_628,
              label: '表单管理查询',
              weight: 1,
            },
            {
              id: 11_645,
              parentId: 11_628,
              label: '表单管理新增',
              weight: 2,
            },
            {
              id: 11_646,
              parentId: 11_628,
              label: '表单管理修改',
              weight: 3,
            },
            {
              id: 11_647,
              parentId: 11_628,
              label: '表单管理删除',
              weight: 4,
            },
            {
              id: 11_648,
              parentId: 11_628,
              label: '表单管理导出',
              weight: 5,
            },
          ],
        },
      ],
    },
    {
      id: 11_618,
      parentId: 0,
      label: 'menu.task.root',
      weight: 7,
      children: [
        {
          id: 11_629,
          parentId: 11_618,
          label: 'menu.task.apply',
          weight: 1,
        },
        {
          id: 11_619,
          parentId: 11_618,
          label: 'menu.task.todo',
          weight: 2,
        },
        {
          id: 11_632,
          parentId: 11_618,
          label: 'menu.task.done',
          weight: 3,
        },
        {
          id: 11_633,
          parentId: 11_618,
          label: 'menu.task.cc',
          weight: 4,
        },
      ],
    },
    {
      id: '1752717490914430978',
      parentId: 0,
      label: '非官方功能',
      weight: 8,
      children: [
        {
          id: '1752717707583787010',
          parentId: '1752717490914430978',
          label: '访问统计',
          weight: 1,
        },
        {
          id: '1728330982004617217',
          parentId: '1752717490914430978',
          label: '发送消息测试',
          weight: 8,
        },
        {
          id: '1801920385979580417',
          parentId: '1752717490914430978',
          label: '文件上传demo',
          weight: 9,
        },
        {
          id: '1808401715449401345',
          parentId: '1752717490914430978',
          label: '富文本编辑器',
          weight: 10,
        },
        {
          id: '1804484510018502658',
          parentId: '1752717490914430978',
          label: '更新日志',
          weight: 22,
        },
        {
          id: '1844262955958992898',
          parentId: '1752717490914430978',
          label: '路由参数示例',
          weight: 23,
        },
      ],
    },
    {
      id: '1754765339911098369',
      parentId: 0,
      label: '微信群',
      weight: 9,
    },
    {
      id: '1746459036148088834',
      parentId: 0,
      label: '外链测试',
      weight: 11,
      children: [
        {
          id: '1746460396327321602',
          parentId: '1746459036148088834',
          label: '项目地址(外链)',
          weight: 1,
        },
        {
          id: '1746459334774145025',
          parentId: '1746459036148088834',
          label: '官方文档(内嵌)',
          weight: 2,
        },
        {
          id: '1760597980791017474',
          parentId: '1746459036148088834',
          label: 'PULS官网',
          weight: 10,
        },
      ],
    },
  ],
};

export const deptTreeData = {
  code: 200,
  msg: '操作成功',
  data: {
    checkedKeys: [105],
    depts: [
      {
        id: 100,
        parentId: 0,
        label: 'XXX科技',
        weight: 0,
        children: [
          {
            id: 101,
            parentId: 100,
            label: '深圳总公司',
            weight: 1,
            children: [
              {
                id: 103,
                parentId: 101,
                label: '研发部门',
                weight: 1,
              },
              {
                id: 104,
                parentId: 101,
                label: '市场部门',
                weight: 2,
              },
              {
                id: 105,
                parentId: 101,
                label: '测试部门',
                weight: 3,
              },
              {
                id: 106,
                parentId: 101,
                label: '财务部门',
                weight: 4,
              },
              {
                id: 107,
                parentId: 101,
                label: '运维部门',
                weight: 5,
              },
            ],
          },
          {
            id: 102,
            parentId: 100,
            label: '长沙分公司',
            weight: 2,
            children: [
              {
                id: 108,
                parentId: 102,
                label: '市场部门',
                weight: 1,
              },
              {
                id: 109,
                parentId: 102,
                label: '财务部门',
                weight: 2,
              },
            ],
          },
        ],
      },
    ],
  },
};

export const userDetailData = {
  code: 200,
  msg: '操作成功',
  data: {
    roleId: 2,
    roleName: '普通角色',
    roleKey: 'common',
    roleSort: 2,
    dataScope: '2',
    menuCheckStrictly: true,
    deptCheckStrictly: true,
    status: '0',
    remark: '普通角色',
    createTime: '2023-11-25 13:06:29',
    flag: false,
    superAdmin: false,
  },
};
