export default {
  total: 5,
  items: [
    {
      roleId: 1,
      roleName: '超级管理员',
      roleKey: 'superadmin',
      roleSort: 1,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '超级管理员',
      createTime: '2023-11-25 13:06:29',
      flag: false,
      superAdmin: true,
    },
    {
      roleId: 2,
      roleName: '普通角色',
      roleKey: 'common',
      roleSort: 2,
      dataScope: '2',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '普通角色',
      createTime: '2023-11-25 13:06:29',
      flag: false,
      superAdmin: false,
    },
    {
      roleId: '1754305165870075906',
      roleName: '部门负责人角色',
      roleKey: 'deptRole',
      roleSort: 3,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-02-05 08:45:20',
      flag: false,
      superAdmin: false,
    },
    {
      roleId: '1785915261624356866',
      roleName: '工作流测试角色',
      roleKey: 'workflow',
      roleSort: 4,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-05-02 14:12:34',
      flag: false,
      superAdmin: false,
    },
    {
      roleId: '1812062772839682049',
      roleName: 'AC测试',
      roleKey: 'AC',
      roleSort: 5,
      dataScope: '1',
      menuCheckStrictly: true,
      deptCheckStrictly: true,
      status: '0',
      remark: '',
      createTime: '2024-07-13 17:53:26',
      flag: false,
      superAdmin: false,
    },
  ],
  code: 200,
  msg: '查询成功',
};
