export const data = {
  code: 200,
  msg: '操作成功',
  message: 'ok',
  error: null,
  data: {
    total: 145,
    items: [
      {
        menuId: 1,
        menuName: '系统管理',
        parentId: 0,
        orderNum: 1,
        path: 'system',
        component: null,
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'eos-icons:system-group',
        createDept: 103,
        remark: '系统管理目录',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 6,
        menuName: '租户管理',
        parentId: 0,
        orderNum: 2,
        path: 'tenant',
        component: null,
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'ic:baseline-house',
        createDept: 103,
        remark: '租户管理目录',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 2,
        menuName: '系统监控',
        parentId: 0,
        orderNum: 3,
        path: 'monitor',
        component: null,
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'solar:monitor-bold-duotone',
        createDept: 103,
        remark: '系统监控目录',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 3,
        menuName: '系统工具',
        parentId: 0,
        orderNum: 4,
        path: 'tool',
        component: null,
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'mdi:tools',
        createDept: 103,
        remark: '系统工具目录',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: '1794635477926084610',
        menuName: '流程发起',
        parentId: 0,
        orderNum: 5,
        path: 'workflow_launch',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'ant-design:ci-twotone',
        createDept: 103,
        remark: '',
        createTime: '2024-05-26 15:43:35',
        children: [],
      },
      {
        menuId: 11_616,
        menuName: '工作流',
        parentId: 0,
        orderNum: 6,
        path: 'workflow',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'mdi:workflow-outline',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_618,
        menuName: '我的任务',
        parentId: 0,
        orderNum: 7,
        path: 'task',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'carbon:task-approved',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: '1752717490914430978',
        menuName: '非官方功能',
        parentId: 0,
        orderNum: 8,
        path: 'function',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'logos:google-cloud-functions',
        createDept: 103,
        remark: '',
        createTime: '2024-01-31 23:36:28',
        children: [],
      },
      {
        menuId: '1754765339911098369',
        menuName: '微信群',
        parentId: 0,
        orderNum: 9,
        path: 'wechat',
        component: '演示使用自行删除/wechat/index',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: null,
        icon: 'mdi:wechat',
        createDept: 103,
        remark: '',
        createTime: '2024-02-06 15:13:54',
        children: [],
      },
      {
        menuId: '1746459036148088834',
        menuName: '外链测试',
        parentId: 0,
        orderNum: 11,
        path: 'link',
        component: null,
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: null,
        icon: 'material-symbols:link',
        createDept: 103,
        remark: '',
        createTime: '2024-01-14 17:07:37',
        children: [],
      },
      {
        menuId: 100,
        menuName: '用户管理',
        parentId: 1,
        orderNum: 1,
        path: 'user',
        component: 'system/user/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:user:list',
        icon: 'ph:user-duotone',
        createDept: 103,
        remark: '用户管理菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 101,
        menuName: '角色管理',
        parentId: 1,
        orderNum: 2,
        path: 'role',
        component: 'system/role/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:role:list',
        icon: 'eos-icons:role-binding-outlined',
        createDept: 103,
        remark: '角色管理菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 102,
        menuName: '菜单管理',
        parentId: 1,
        orderNum: 3,
        path: 'menu',
        component: 'system/menu/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:menu:list',
        icon: 'ic:sharp-menu',
        createDept: 103,
        remark: '菜单管理菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 103,
        menuName: '部门管理',
        parentId: 1,
        orderNum: 4,
        path: 'dept',
        component: 'system/dept/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:dept:list',
        icon: 'mingcute:department-line',
        createDept: 103,
        remark: '部门管理菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 104,
        menuName: '岗位管理',
        parentId: 1,
        orderNum: 5,
        path: 'post',
        component: 'system/post/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:post:list',
        icon: 'icon-park-outline:appointment',
        createDept: 103,
        remark: '岗位管理菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 105,
        menuName: '字典管理',
        parentId: 1,
        orderNum: 6,
        path: 'dict',
        component: 'system/dict/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:dict:list',
        icon: 'fluent-mdl2:dictionary',
        createDept: 103,
        remark: '字典管理菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 106,
        menuName: '参数设置',
        parentId: 1,
        orderNum: 7,
        path: 'config',
        component: 'system/config/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:config:list',
        icon: 'icon-park-twotone:setting-two',
        createDept: 103,
        remark: '参数设置菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 107,
        menuName: '通知公告',
        parentId: 1,
        orderNum: 8,
        path: 'notice',
        component: 'system/notice/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:notice:list',
        icon: 'fe:notice-push',
        createDept: 103,
        remark: '通知公告菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 108,
        menuName: '日志管理',
        parentId: 1,
        orderNum: 9,
        path: 'log',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'material-symbols:logo-dev-outline',
        createDept: 103,
        remark: '日志管理菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 118,
        menuName: '文件管理',
        parentId: 1,
        orderNum: 10,
        path: 'oss',
        component: 'system/oss/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:oss:list',
        icon: 'solar:folder-with-files-outline',
        createDept: 103,
        remark: '文件管理菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 123,
        menuName: '客户端管理',
        parentId: 1,
        orderNum: 11,
        path: 'client',
        component: 'system/client/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:client:list',
        icon: 'simple-icons:authy',
        createDept: 103,
        remark: '客户端管理菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 109,
        menuName: '在线用户',
        parentId: 2,
        orderNum: 1,
        path: 'online',
        component: 'monitor/online/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:online:list',
        icon: 'material-symbols:generating-tokens-outline',
        createDept: 103,
        remark: '在线用户菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 113,
        menuName: '缓存监控',
        parentId: 2,
        orderNum: 5,
        path: 'cache',
        component: 'monitor/cache/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:cache:list',
        icon: 'devicon:redis-wordmark',
        createDept: 103,
        remark: '缓存监控菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 117,
        menuName: 'Admin监控',
        parentId: 2,
        orderNum: 5,
        path: 'https://www.antdv.com/components/empty-cn',
        component: '',
        queryParam: '',
        isFrame: '0',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:admin:list',
        icon: 'devicon:spring-wordmark',
        createDept: 103,
        remark: 'Admin监控菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 120,
        menuName: '任务调度中心',
        parentId: 2,
        orderNum: 5,
        path: 'https://snailjob.opensnail.com/',
        component: '',
        queryParam: '',
        isFrame: '0',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:snailjob:list',
        icon: 'akar-icons:schedule',
        createDept: 103,
        remark: 'SnailJob控制台菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 115,
        menuName: '代码生成',
        parentId: 3,
        orderNum: 2,
        path: 'gen',
        component: 'tool/gen/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'tool:gen:list',
        icon: 'tabler:code',
        createDept: 103,
        remark: '代码生成菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 121,
        menuName: '租户管理',
        parentId: 6,
        orderNum: 1,
        path: 'tenant',
        component: 'system/tenant/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:tenant:list',
        icon: 'bi:houses-fill',
        createDept: 103,
        remark: '租户管理菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 122,
        menuName: '租户套餐管理',
        parentId: 6,
        orderNum: 2,
        path: 'tenantPackage',
        component: 'system/tenantPackage/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:list',
        icon: 'bx:package',
        createDept: 103,
        remark: '租户套餐管理菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1001,
        menuName: '用户查询',
        parentId: 100,
        orderNum: 1,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1002,
        menuName: '用户新增',
        parentId: 100,
        orderNum: 2,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1003,
        menuName: '用户修改',
        parentId: 100,
        orderNum: 3,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1004,
        menuName: '用户删除',
        parentId: 100,
        orderNum: 4,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1005,
        menuName: '用户导出',
        parentId: 100,
        orderNum: 5,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1006,
        menuName: '用户导入',
        parentId: 100,
        orderNum: 6,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:import',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1007,
        menuName: '重置密码',
        parentId: 100,
        orderNum: 7,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:user:resetPwd',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1008,
        menuName: '角色查询',
        parentId: 101,
        orderNum: 1,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1009,
        menuName: '角色新增',
        parentId: 101,
        orderNum: 2,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1010,
        menuName: '角色修改',
        parentId: 101,
        orderNum: 3,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1011,
        menuName: '角色删除',
        parentId: 101,
        orderNum: 4,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1012,
        menuName: '角色导出',
        parentId: 101,
        orderNum: 5,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:role:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1013,
        menuName: '菜单查询',
        parentId: 102,
        orderNum: 1,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1014,
        menuName: '菜单新增',
        parentId: 102,
        orderNum: 2,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1015,
        menuName: '菜单修改',
        parentId: 102,
        orderNum: 3,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1016,
        menuName: '菜单删除',
        parentId: 102,
        orderNum: 4,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:menu:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1017,
        menuName: '部门查询',
        parentId: 103,
        orderNum: 1,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1018,
        menuName: '部门新增',
        parentId: 103,
        orderNum: 2,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1019,
        menuName: '部门修改',
        parentId: 103,
        orderNum: 3,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1020,
        menuName: '部门删除',
        parentId: 103,
        orderNum: 4,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dept:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1021,
        menuName: '岗位查询',
        parentId: 104,
        orderNum: 1,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1022,
        menuName: '岗位新增',
        parentId: 104,
        orderNum: 2,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1023,
        menuName: '岗位修改',
        parentId: 104,
        orderNum: 3,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1024,
        menuName: '岗位删除',
        parentId: 104,
        orderNum: 4,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1025,
        menuName: '岗位导出',
        parentId: 104,
        orderNum: 5,
        path: '',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:post:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1026,
        menuName: '字典查询',
        parentId: 105,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1027,
        menuName: '字典新增',
        parentId: 105,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1028,
        menuName: '字典修改',
        parentId: 105,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1029,
        menuName: '字典删除',
        parentId: 105,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1030,
        menuName: '字典导出',
        parentId: 105,
        orderNum: 5,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:dict:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1031,
        menuName: '参数查询',
        parentId: 106,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1032,
        menuName: '参数新增',
        parentId: 106,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1033,
        menuName: '参数修改',
        parentId: 106,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1034,
        menuName: '参数删除',
        parentId: 106,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1035,
        menuName: '参数导出',
        parentId: 106,
        orderNum: 5,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:config:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1036,
        menuName: '公告查询',
        parentId: 107,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1037,
        menuName: '公告新增',
        parentId: 107,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1038,
        menuName: '公告修改',
        parentId: 107,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1039,
        menuName: '公告删除',
        parentId: 107,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:notice:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 500,
        menuName: '操作日志',
        parentId: 108,
        orderNum: 1,
        path: 'operlog',
        component: 'monitor/operlog/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:list',
        icon: 'arcticons:one-hand-operation',
        createDept: 103,
        remark: '操作日志菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 501,
        menuName: '登录日志',
        parentId: 108,
        orderNum: 2,
        path: 'logininfor',
        component: 'monitor/logininfor/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:list',
        icon: 'streamline:interface-login-dial-pad-finger-password-dial-pad-dot-finger',
        createDept: 103,
        remark: '登录日志菜单',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1046,
        menuName: '在线查询',
        parentId: 109,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:online:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1047,
        menuName: '批量强退',
        parentId: 109,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:online:batchLogout',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1048,
        menuName: '单条强退',
        parentId: 109,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:online:forceLogout',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1055,
        menuName: '生成查询',
        parentId: 115,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1056,
        menuName: '生成修改',
        parentId: 115,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1058,
        menuName: '导入代码',
        parentId: 115,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:import',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1057,
        menuName: '生成删除',
        parentId: 115,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1059,
        menuName: '预览代码',
        parentId: 115,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:preview',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1060,
        menuName: '生成代码',
        parentId: 115,
        orderNum: 5,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'tool:gen:code',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1600,
        menuName: '文件查询',
        parentId: 118,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:oss:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1601,
        menuName: '文件上传',
        parentId: 118,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:oss:upload',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1602,
        menuName: '文件下载',
        parentId: 118,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:oss:download',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1603,
        menuName: '文件删除',
        parentId: 118,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:oss:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1620,
        menuName: '配置列表',
        parentId: 118,
        orderNum: 5,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:ossConfig:list',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-10-06 17:06:07',
        children: [],
      },
      {
        menuId: 1621,
        menuName: '配置添加',
        parentId: 118,
        orderNum: 6,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:ossConfig:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-10-06 17:06:07',
        children: [],
      },
      {
        menuId: 1622,
        menuName: '配置编辑',
        parentId: 118,
        orderNum: 6,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:ossConfig:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-10-06 17:06:07',
        children: [],
      },
      {
        menuId: 1623,
        menuName: '配置删除',
        parentId: 118,
        orderNum: 6,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:ossConfig:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-10-06 17:06:07',
        children: [],
      },
      {
        menuId: 1606,
        menuName: '租户查询',
        parentId: 121,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenant:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1607,
        menuName: '租户新增',
        parentId: 121,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenant:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1608,
        menuName: '租户修改',
        parentId: 121,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenant:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1609,
        menuName: '租户删除',
        parentId: 121,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenant:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1610,
        menuName: '租户导出',
        parentId: 121,
        orderNum: 5,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenant:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1611,
        menuName: '租户套餐查询',
        parentId: 122,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1612,
        menuName: '租户套餐新增',
        parentId: 122,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1613,
        menuName: '租户套餐修改',
        parentId: 122,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1614,
        menuName: '租户套餐删除',
        parentId: 122,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1615,
        menuName: '租户套餐导出',
        parentId: 122,
        orderNum: 5,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:tenantPackage:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1061,
        menuName: '客户端管理查询',
        parentId: 123,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:client:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1062,
        menuName: '客户端管理新增',
        parentId: 123,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:client:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1063,
        menuName: '客户端管理修改',
        parentId: 123,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:client:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1064,
        menuName: '客户端管理删除',
        parentId: 123,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:client:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1065,
        menuName: '客户端管理导出',
        parentId: 123,
        orderNum: 5,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'system:client:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1040,
        menuName: '操作查询',
        parentId: 500,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1041,
        menuName: '操作删除',
        parentId: 500,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1042,
        menuName: '日志导出',
        parentId: 500,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:operlog:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1043,
        menuName: '登录查询',
        parentId: 501,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1044,
        menuName: '登录删除',
        parentId: 501,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1045,
        menuName: '日志导出',
        parentId: 501,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 1050,
        menuName: '账户解锁',
        parentId: 501,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'monitor:logininfor:unlock',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 13:06:29',
        children: [],
      },
      {
        menuId: 11_622,
        menuName: '流程分类',
        parentId: 11_616,
        orderNum: 1,
        path: 'category',
        component: 'workflow/category/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'workflow:category:list',
        icon: 'tabler:category-plus',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_617,
        menuName: '模型管理',
        parentId: 11_616,
        orderNum: 2,
        path: 'model',
        component: 'workflow/model/index',
        queryParam: '',
        isFrame: '1',
        isCache: '1',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'workflow:model:list',
        icon: 'carbon:model-alt',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_620,
        menuName: '流程定义',
        parentId: 11_616,
        orderNum: 3,
        path: 'processDefinition',
        component: 'workflow/processDefinition/index',
        queryParam: '',
        isFrame: '1',
        isCache: '1',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'fluent-mdl2:build-definition',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_630,
        menuName: '流程监控',
        parentId: 11_616,
        orderNum: 4,
        path: 'monitor',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'icon-park-outline:monitor',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_628,
        menuName: '表单管理',
        parentId: 11_616,
        orderNum: 5,
        path: 'formManage',
        component: 'workflow/formManage/index',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'workflow:formManage:list',
        icon: 'fluent:form-24-regular',
        createDept: 103,
        remark: '表单管理菜单',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_629,
        menuName: '我发起的',
        parentId: 11_618,
        orderNum: 1,
        path: 'myDocument',
        component: 'workflow/task/myDocument',
        queryParam: '',
        isFrame: '1',
        isCache: '1',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'ic:round-launch',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_619,
        menuName: '我的待办',
        parentId: 11_618,
        orderNum: 2,
        path: 'taskWaiting',
        component: 'workflow/task/taskWaiting',
        queryParam: '',
        isFrame: '1',
        isCache: '1',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'streamline:waiting-appointments-calendar',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_632,
        menuName: '我的已办',
        parentId: 11_618,
        orderNum: 3,
        path: 'taskFinish',
        component: 'workflow/task/taskFinish',
        queryParam: '',
        isFrame: '1',
        isCache: '1',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'material-symbols:cloud-done-outline-rounded',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_633,
        menuName: '我的抄送',
        parentId: 11_618,
        orderNum: 4,
        path: 'taskCopyList',
        component: 'workflow/task/taskCopyList',
        queryParam: '',
        isFrame: '1',
        isCache: '1',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'mdi:cc-outline',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_623,
        menuName: '流程分类查询',
        parentId: 11_622,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:category:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_624,
        menuName: '流程分类新增',
        parentId: 11_622,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:category:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_625,
        menuName: '流程分类修改',
        parentId: 11_622,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:category:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_626,
        menuName: '流程分类删除',
        parentId: 11_622,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:category:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_627,
        menuName: '流程分类导出',
        parentId: 11_622,
        orderNum: 5,
        path: '#',
        component: '',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:category:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_644,
        menuName: '表单管理查询',
        parentId: 11_628,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:formManage:query',
        icon: '',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_645,
        menuName: '表单管理新增',
        parentId: 11_628,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:formManage:add',
        icon: '',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_646,
        menuName: '表单管理修改',
        parentId: 11_628,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:formManage:edit',
        icon: '',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_647,
        menuName: '表单管理删除',
        parentId: 11_628,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:formManage:remove',
        icon: '',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_648,
        menuName: '表单管理导出',
        parentId: 11_628,
        orderNum: 5,
        path: '#',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:formManage:export',
        icon: 'tree-table',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_621,
        menuName: '流程实例',
        parentId: 11_630,
        orderNum: 1,
        path: 'processInstance',
        component: 'workflow/processInstance/index',
        queryParam: '',
        isFrame: '1',
        isCache: '1',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'ri:instance-line',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_631,
        menuName: '待办任务',
        parentId: 11_630,
        orderNum: 2,
        path: 'allTaskWaiting',
        component: 'workflow/task/allTaskWaiting',
        queryParam: '',
        isFrame: '1',
        isCache: '1',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'streamline:waiting-appointments-calendar',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_639,
        menuName: '请假申请查询',
        parentId: 11_638,
        orderNum: 1,
        path: '#',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:leave:query',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_640,
        menuName: '请假申请新增',
        parentId: 11_638,
        orderNum: 2,
        path: '#',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:leave:add',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_641,
        menuName: '请假申请修改',
        parentId: 11_638,
        orderNum: 3,
        path: '#',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:leave:edit',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_642,
        menuName: '请假申请删除',
        parentId: 11_638,
        orderNum: 4,
        path: '#',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:leave:remove',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: 11_643,
        menuName: '请假申请导出',
        parentId: 11_638,
        orderNum: 5,
        path: '#',
        component: '',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'F',
        visible: '0',
        status: '0',
        perms: 'workflow:leave:export',
        icon: '#',
        createDept: 103,
        remark: '',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
      {
        menuId: '1746460396327321602',
        menuName: '项目地址(外链)',
        parentId: '1746459036148088834',
        orderNum: 1,
        path: 'https://gitee.com/dapppp/ruoyi-plus-vben',
        component: null,
        queryParam: null,
        isFrame: '0',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: null,
        icon: 'simple-icons:gitee',
        createDept: 103,
        remark: '',
        createTime: '2024-01-14 17:13:01',
        children: [],
      },
      {
        menuId: '1746459334774145025',
        menuName: '官方文档(内嵌)',
        parentId: '1746459036148088834',
        orderNum: 2,
        path: 'https://plus-doc.dromara.org/#/README',
        component: null,
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: null,
        icon: 'simple-icons:gitee',
        createDept: 103,
        remark: '',
        createTime: '2024-01-14 17:08:48',
        children: [],
      },
      {
        menuId: '1760597980791017474',
        menuName: 'PULS官网',
        parentId: '1746459036148088834',
        orderNum: 10,
        path: 'https://gitee.com/dapppp/ruoyi-plus-vben',
        component: '',
        queryParam: null,
        isFrame: '0',
        isCache: '0',
        menuType: 'M',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'ant-design:ant-design-outlined',
        createDept: 103,
        remark: '',
        createTime: '2024-02-22 17:30:44',
        children: [],
      },
      {
        menuId: '1752717707583787010',
        menuName: '访问统计',
        parentId: '1752717490914430978',
        orderNum: 1,
        path: 'visit',
        component: '演示使用自行删除/visit/index',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: null,
        icon: 'icon-park:record-disc',
        createDept: 103,
        remark: '',
        createTime: '2024-01-31 23:37:20',
        children: [],
      },
      {
        menuId: '1827607544505892865',
        menuName: 'Gitee统计',
        parentId: '1752717490914430978',
        orderNum: 8,
        path: 'gitee',
        component: '演示使用自行删除/gitee/index',
        queryParam: '',
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'simple-icons:gitee',
        createDept: 100,
        remark: '',
        createTime: '2024-08-25 15:22:49',
        children: [],
      },
      {
        menuId: '1728330982004617217',
        menuName: '发送消息测试',
        parentId: '1752717490914430978',
        orderNum: 8,
        path: 'websocket',
        component: '演示使用自行删除/sse/index',
        queryParam: null,
        isFrame: '1',
        isCache: '1',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: null,
        icon: 'icon-park:round-socket',
        createDept: 103,
        remark: '',
        createTime: '2023-11-25 16:33:12',
        children: [],
      },
      {
        menuId: '1801920385979580417',
        menuName: '文件上传demo',
        parentId: '1752717490914430978',
        orderNum: 9,
        path: 'image-demo',
        component: '演示使用自行删除/upload/index',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'fa6-regular:image',
        createDept: 103,
        remark: '',
        createTime: '2024-06-15 18:11:13',
        children: [],
      },
      {
        menuId: '1808401715449401345',
        menuName: '富文本编辑器',
        parentId: '1752717490914430978',
        orderNum: 10,
        path: 'tinymce',
        component: '演示使用自行删除/tinymce/index',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'icon-park-outline:editor',
        createDept: 100,
        remark: '',
        createTime: '2024-07-03 15:25:42',
        children: [],
      },
      {
        menuId: '1804484510018502658',
        menuName: '更新日志',
        parentId: '1752717490914430978',
        orderNum: 22,
        path: 'changelog',
        component: '演示使用自行删除/changelog/index',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'ic:baseline-update',
        createDept: 100,
        remark: '',
        createTime: '2024-06-22 20:00:08',
        children: [],
      },
      {
        menuId: '1794636509859086338',
        menuName: '采购流程(子表单)',
        parentId: '1794635477926084610',
        orderNum: 2,
        path: 'purchase',
        component: 'demo/subform/index',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: '',
        icon: 'noto:shopping-cart',
        createDept: 103,
        remark: '',
        createTime: '2024-05-26 15:47:41',
        children: [],
      },
      {
        menuId: 11_638,
        menuName: '请假申请',
        parentId: '1794635477926084610',
        orderNum: 5,
        path: 'leave',
        component: 'workflow/leave/index',
        queryParam: null,
        isFrame: '1',
        isCache: '0',
        menuType: 'C',
        visible: '0',
        status: '0',
        perms: 'workflow:leave:list',
        icon: 'fluent-mdl2:leave-user',
        createDept: 103,
        remark: '请假申请菜单',
        createTime: '2024-05-02 13:26:47',
        children: [],
      },
    ],
  },
};
