name: Release To Ali Server

on:
  push:
    branches:
      - ruoyi-vben

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup pivate npm registry
        # run: |
        #   pnpm config set registry https://packages.aliyun.com/66e16550691d6fdafb3cb0a1/npm/npm-registry/
        #   pnpm config set //packages.aliyun.com/66e16550691d6fdafb3cb0a1/npm/npm-registry/:_authToken ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          pnpm config set registry https://packages.aliyun.com/66e16550691d6fdafb3cb0a1/npm/npm-registry/
          pnpm config set //packages.aliyun.com/66e16550691d6fdafb3cb0a1/npm/npm-registry/:_authToken "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Install Private Dependencies
        run: pnpm install @zyy/pivot-table --filter @vben/web-antd

      - name: Setup npm registry
        run: pnpm config set registry https://registry.npmmirror.com

      - name: Install Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:antd

      - name: Deploy to Aliyun Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: -rltgoDzvO --delete
          SOURCE: apps/web-antd/dist/
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
